version: '3.8'

services:
  db:
    image: postgres:16.11
    container_name: postgres-db
    environment:
      - POSTGRES_DB=backendengineering
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5000:5432"

volumes:
  db-data: